### ISSUE TITLE
巨大的局限性

### ISSUE THREAD

**Issue by jf3096** [tywei90/pagemaker_production#1]
抛开技术实现，目前工具可视化无法满足复杂的场景，即使能够使用jscss的组件。

1. 跟官网不一样，官网的界面显示可以自定义创建组件，但是这个不行。
2. 对于复杂的UI场景难以适应，不如struct。
3. 当遇到复杂交互时，需要前端人员开发，那么这个时候相当尴尬，一是被当前工具局限了很多使用，如第三方插件。二是运营人员无法完全自行管理页面，仍需运营和前端同学协同开发

**Comment by tywei90** [comment]
你说的官网应该是指网易乐得的nfop系统吧。这个是内部项目，很多人开发维护的，我这只是自己做的一个pagemaker简单实现，用的一整套react技术栈，做一个供大家学习的demo而已。
你说的官网可以自定义创建组件我不知道你从何得知的，我知道的只是你能自己选择相应的组件，比如轮播图，但是不能自定义。有某个组件额需求，可以开发
当然，开源出来就是想让大家一起维护，后续可以加入各种组件的支持。
对于复杂页面，当然还是需要前端人员自己开发了，工具终究是工具，只能在简单的页面上代替开发，不然我们前端人员可以失业了

**Comment by jf3096** [comment]
我了解你的意图了，只是这样的工具难以走远。我也在走这么一条道，基本的需求你可以参考一下[structor](https://github.com/ipselon/structor)。

**Comment by tywei90** [comment]
我看了下，东西确实比较多，对于产品和运营上手可能还需要一些学习成本。但是为啥没有线上地址呢？相比之下，pagemaker可以很方便上线和修改
